### ISSUE TITLE
REST API should make product column GUID uppercase

### ISSUE THREAD

**Issue by jonaskello** [promaster-sdk/api-server#15]
For historical reasons the REST API exposes GUID in uppercase. Conversions are made for example in places like this:

https://github.com/promaster-sdk/api-server/blob/master/src/client-rest/middleware.ts#L384

However if a table has a column of type product this conversion is node made so the GUID of the product is exposed as lowercase. This causes problems for applications that does string comparisons of GUID. To help these applications REST API should consistently expose all GUID as uppercase.

**Comment by esakylli** [comment]
Fixed

**Comment by jonaskello** [comment]
@esakylli Could you also update the [changelog](https://github.com/promaster-sdk/api-server/blob/master/CHANGELOG.md)?
